#!/usr/bin/env python3
"""
Fetch London borough boundaries from martinjc/UK-GeoJSON TopoJSON,
project to SVG coordinates, and write src/data/london-borough-paths.ts.

Run: python3 src/scripts/generate-london-map.py
"""
import json, urllib.request, math, os, re

TOPOJSON_URL = (
    "https://raw.githubusercontent.com/martinjc/UK-GeoJSON/master"
    "/json/administrative/eng/topo_lad.json"
)

# London borough GSS codes (E09000001–E09000033)
LONDON_CODES = {f"E09{i:06d}" for i in range(1, 34)}

# SVG viewport
SVG_W = 800
SVG_H = 600

# London bounding box in WGS84 (lon/lat)
LON_MIN, LON_MAX = -0.535, 0.355
LAT_MIN, LAT_MAX = 51.25,  51.71


def project(lon: float, lat: float):
    x = ((lon - LON_MIN) / (LON_MAX - LON_MIN)) * SVG_W
    y = ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * SVG_H
    return x, y


def resolve_arcs(topo_arcs, transform):
    """Convert TopoJSON delta-encoded arcs → list of (lon, lat) coordinate lists."""
    sx, sy = transform["scale"]
    tx, ty = transform["translate"]
    resolved = []
    for arc in topo_arcs:
        coords = []
        cx, cy = 0, 0
        for dx, dy in arc:
            cx += dx
            cy += dy
            lon = cx * sx + tx
            lat = cy * sy + ty
            coords.append((lon, lat))
        resolved.append(coords)
    return resolved


def arc_to_points(arc_idx: int, resolved_arcs):
    """Return coordinate list for an arc index (negative = reversed)."""
    if arc_idx < 0:
        return list(reversed(resolved_arcs[~arc_idx]))
    return resolved_arcs[arc_idx]


def ring_to_svg(arc_indices, resolved_arcs) -> str:
    points = []
    for idx in arc_indices:
        seg = arc_to_points(idx, resolved_arcs)
        # Skip duplicate junction point between consecutive arcs
        if points:
            seg = seg[1:]
        points.extend(seg)
    if not points:
        return ""
    parts = []
    for i, (lon, lat) in enumerate(points):
        x, y = project(lon, lat)
        cmd = "M" if i == 0 else "L"
        parts.append(f"{cmd}{x:.1f},{y:.1f}")
    parts.append("Z")
    return " ".join(parts)


def geom_to_path(geom, resolved_arcs) -> str:
    gtype = geom["type"]
    if gtype == "Polygon":
        return " ".join(
            ring_to_svg(ring, resolved_arcs)
            for ring in geom["arcs"]
        )
    elif gtype == "MultiPolygon":
        return " ".join(
            " ".join(ring_to_svg(ring, resolved_arcs) for ring in polygon)
            for polygon in geom["arcs"]
        )
    return ""


def main():
    print(f"Fetching TopoJSON from {TOPOJSON_URL} ...")
    with urllib.request.urlopen(TOPOJSON_URL) as resp:
        topo = json.load(resp)

    transform = topo["transform"]
    resolved_arcs = resolve_arcs(topo["arcs"], transform)

    geometries = topo["objects"]["lad"]["geometries"]
    london_geoms = [
        g for g in geometries
        if g["properties"]["LAD13CD"] in LONDON_CODES
    ]
    print(f"Found {len(london_geoms)} London borough geometries")

    borough_paths = {}
    for geom in london_geoms:
        name = geom["properties"]["LAD13NM"]
        path = geom_to_path(geom, resolved_arcs)
        if path:
            borough_paths[name] = path

    # Write TypeScript constant
    out_path = os.path.join(
        os.path.dirname(__file__), "..", "data", "london-borough-paths.ts"
    )
    out_path = os.path.normpath(out_path)

    json_str = json.dumps(borough_paths, indent=2)
    ts_content = f"""// Auto-generated by src/scripts/generate-london-map.py
// DO NOT EDIT MANUALLY — re-run the script to regenerate
// Source: martinjc/UK-GeoJSON (ONS boundaries, WGS84 → SVG 800×600)

export const BOROUGH_PATHS: Record<string, string> = {json_str}
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(ts_content)

    print(f"Written {len(borough_paths)} borough paths to {out_path}")
    print("Boroughs:", ", ".join(sorted(borough_paths.keys())))


if __name__ == "__main__":
    main()
